apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: agrosolutions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: admin-password
          volumeMounts:
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/dashboards/dashboard.yaml
              subPath: dashboard-provider.yaml
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
            - name: grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards/dashboard.json
              subPath: dashboard.json
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-provisioning
          configMap:
            name: grafana-provisioning
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboard
        - name: grafana-storage
          emptyDir: {}