apiVersion: v1
kind: Secret
metadata:
  name: ingestion-service-secret
  namespace: agrosolutions
type: Opaque
data:
  Jwt__Key: QWdyb1NvbHV0aW9ucy1TZWNyZXQtS2V5LUZvci1KV1QtQXV0aGVudGljYXRpb24tMjAyNA==
  RabbitMQ__Username: Z3Vlc3Q=
  RabbitMQ__Password: Z3Vlc3Q=
