FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/AlertService/AlertService.csproj", "src/AlertService/"]
COPY ["src/Shared/Shared.csproj", "src/Shared/"]
RUN dotnet restore "src/AlertService/AlertService.csproj"
COPY . .
WORKDIR "/src/src/AlertService"
RUN dotnet build "AlertService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AlertService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AlertService.dll"]
