apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  namespace: agrosolutions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
        - name: alert-service
          image: ghcr.io/thiagoreboredo/agrosolutions/alert-service:latest
          envFrom:
            - configMapRef:
                name: alert-service-config
            - secretRef:
                name: alert-service-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
