apiVersion: v1
kind: Secret
metadata:
  name: alert-service-secret
  namespace: agrosolutions
type: Opaque
stringData:
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"
  InternalApiKey: "internal-agrosolutions-api-key-change-in-production"