apiVersion: v1
kind: Secret
metadata:
  name: alert-service-secret
  namespace: agrosolutions
type: Opaque
data:
  RabbitMQ__Username: Z3Vlc3Q=
  RabbitMQ__Password: Z3Vlc3Q=
  InternalApiKey: aW50ZXJuYWwtYWdyb3NvbHV0aW9ucy1hcGkta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
