apiVersion: v1
kind: Secret
metadata:
  name: property-service-secret
  namespace: agrosolutions
type: Opaque
stringData:
  Jwt__Key: "AgroSolutions-Secret-Key-For-JWT-Authentication-2024"
  ConnectionStrings__DefaultConnection: "Host=postgres-postgresql;Database=agrosolutions_db;Username=postgres;Password=buETmdlxQ8"
  InternalApiKey: "internal-agrosolutions-api-key-change-in-production"