apiVersion: v1
kind: Secret
metadata:
  name: identity-service-secret
  namespace: agrosolutions
type: Opaque
data:
  Jwt__Key: QWdyb1NvbHV0aW9ucy1TZWNyZXQtS2V5LUZvci1KV1QtQXV0aGVudGljYXRpb24tMjAyNA==
  ConnectionStrings__DefaultConnection: SG9zdD1wb3N0Z3JlcztEYXRhYmFzZT1pZGVudGl0eV9kYjtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1wb3N0Z3Jlcw==
